eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka
spring:
  cloud:
    config:
      uri: http://config-server
feign:
  hystrix:
    enabled: on
